"""Export warp-debug images for the sample pipeline.

Creates a dedicated debug-only folder and saves every image-space warp
preview needed to inspect ``examples/python/sample.py`` geometry.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import cv2
import numpy as np

from external.GrayCode.src.python.config import (
    reload_config as reload_graycode_config,
)
from examples.python.sample import (
    _create_warper,
    center_rect,
    invwarp_image,
    prepare_target_image_for_compensation,
    resolve_target_image_space,
    resolve_warp_settings,
    warp_image,
)
from src.python.config import get_config, reload_config, split_cli_config_path


DEBUG_DIR_NAME = "debug_warp_outputs_DEBUG_ONLY"
SUPPORTED_IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".bmp", ".tiff")
DEBUG_README = """# DEBUG ONLY

This folder is reserved for warp-debug outputs.

- Generated by `examples/python/debug_warp_outputs.py`
- Safe to delete and regenerate
- Not intended as final pipeline output
"""


def _save_rgb_image(path: Path, image: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    cv2.imwrite(str(path), bgr)


def _write_debug_readme(debug_dir: Path) -> None:
    (debug_dir / "README.md").write_text(DEBUG_README, encoding="utf-8")


def _draw_projector_region(
    proj_width: int,
    proj_height: int,
    crop_rect: tuple[int, int, int, int],
) -> np.ndarray:
    canvas = np.zeros((proj_height, proj_width, 3), dtype=np.uint8)
    x, y, w, h = crop_rect
    if w > 0 and h > 0:
        cv2.rectangle(canvas, (x, y), (x + w - 1, y + h - 1), (0, 255, 0), 2)
    return canvas


def _build_projector_canvas(
    image: np.ndarray,
    proj_width: int,
    proj_height: int,
) -> np.ndarray:
    canvas = np.zeros((proj_height, proj_width, 3), dtype=image.dtype)
    x, y, w, h = center_rect(image.shape[1], image.shape[0], proj_width, proj_height)
    canvas[y : y + h, x : x + w] = image[:h, :w]
    return canvas


def _inspect_warp_map(
    pixel_map_path: str,
    warp_method: str,
    proj_width: int,
    proj_height: int,
) -> dict[str, Any]:
    warper = _create_warper(pixel_map_path, warp_method)
    xy_bounds = [float(v) for v in warper.xy_bounds]
    uv_bounds = [float(v) for v in warper.uv_bounds]

    if warp_method == "c2p":
        inferred_projector = {
            "width": int(uv_bounds[2]) + 1,
            "height": int(uv_bounds[3]) + 1,
        }
        inferred_camera = {
            "width": int(xy_bounds[2] - xy_bounds[0]) + 1,
            "height": int(xy_bounds[3] - xy_bounds[1]) + 1,
        }
    else:
        inferred_projector = {
            "width": int(xy_bounds[2] - xy_bounds[0]) + 1,
            "height": int(xy_bounds[3] - xy_bounds[1]) + 1,
        }
        inferred_camera = {
            "width": int(uv_bounds[2]) + 1,
            "height": int(uv_bounds[3]) + 1,
        }

    warnings: list[str] = []
    if (
        inferred_projector["width"] != proj_width
        or inferred_projector["height"] != proj_height
    ):
        warnings.append(
            "Configured projector size "
            f"{proj_width}x{proj_height} differs from map-derived size "
            f"{inferred_projector['width']}x{inferred_projector['height']}."
        )

    return {
        "xy_bounds": xy_bounds,
        "uv_bounds": uv_bounds,
        "inferred_camera_size": inferred_camera,
        "inferred_projector_size": inferred_projector,
        "warnings": warnings,
    }


def _load_target_images(target_dir: str) -> list[tuple[str, np.ndarray]]:
    images: list[tuple[str, np.ndarray]] = []
    for img_name in sorted(os.listdir(target_dir)):
        if not img_name.lower().endswith(SUPPORTED_IMAGE_SUFFIXES):
            continue
        img_path = Path(target_dir) / img_name
        bgr = cv2.imread(str(img_path), cv2.IMREAD_COLOR)
        if bgr is None:
            continue
        images.append((img_name, cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)))
    return images


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv

    try:
        clean_argv, config_path = split_cli_config_path(argv)
    except ValueError as exc:
        print(f"Invalid CLI arguments: {exc}")
        return 1

    if len(clean_argv) != 1:
        print(
            "Usage: python examples/python/debug_warp_outputs.py "
            "[--config <config.toml>]"
        )
        return 1

    default_config_path = REPO_ROOT / "config.toml"
    effective_config_path = (
        config_path if config_path is not None else default_config_path
    )
    reload_config(effective_config_path)
    reload_graycode_config(effective_config_path)

    cfg = get_config()
    proj = cfg.projector
    paths = cfg.paths

    try:
        warp_method, pixel_map_path = resolve_warp_settings(paths)
        target_image_space = resolve_target_image_space(paths)
    except ValueError as exc:
        print(f"Invalid warp config: {exc}")
        return 1

    debug_dir = Path("data") / DEBUG_DIR_NAME
    debug_dir.mkdir(parents=True, exist_ok=True)
    _write_debug_readme(debug_dir)

    report: dict[str, Any] = {
        "config_path": str(effective_config_path),
        "warp_method": warp_method,
        "target_image_space": target_image_space,
        "pixel_map_path": pixel_map_path,
        "configured_projector_size": {
            "width": proj.width,
            "height": proj.height,
        },
    }

    try:
        map_report = _inspect_warp_map(
            pixel_map_path,
            warp_method,
            proj.width,
            proj.height,
        )
    except FileNotFoundError:
        print(f"Pixel map not found: {pixel_map_path}")
        return 1
    except Exception as exc:
        print(f"Failed to inspect warp map: {exc}")
        return 1

    report["map"] = map_report
    camera_width = int(map_report["inferred_camera_size"]["width"])
    camera_height = int(map_report["inferred_camera_size"]["height"])

    try:
        target_images = _load_target_images(paths.target_image_dir)
    except FileNotFoundError:
        print(f"Target image directory not found: {paths.target_image_dir}")
        return 1

    report["targets"] = []
    all_warnings = list(map_report["warnings"])

    for idx, (img_name, target_image) in enumerate(target_images):
        target_dir = debug_dir / f"{idx:02d}_{Path(img_name).stem}"
        target_dir.mkdir(parents=True, exist_ok=True)

        crop_rect = center_rect(
            target_image.shape[1],
            target_image.shape[0],
            proj.width,
            proj.height,
        )
        target_report: dict[str, Any] = {
            "image_name": img_name,
            "original_shape": list(target_image.shape),
            "crop_rect_in_projector": list(crop_rect),
            "saved_files": [],
            "warnings": [],
        }

        if target_image_space == "camera" and (
            target_image.shape[1] != camera_width
            or target_image.shape[0] != camera_height
        ):
            target_report["warnings"].append(
                "Camera-space target size "
                f"{target_image.shape[1]}x{target_image.shape[0]} does not match "
                f"map-derived camera size {camera_width}x{camera_height}. "
                "sample.py currently interprets such images from camera origin (0, 0)."
            )

        if (
            target_image.shape[1] > proj.width
            or target_image.shape[0] > proj.height
        ):
            target_report["warnings"].append(
                "Target image exceeds projector frame and will be clamped to "
                f"{crop_rect[2]}x{crop_rect[3]} during centered placement."
            )

        original_path = target_dir / "00_original.png"
        _save_rgb_image(original_path, target_image)
        target_report["saved_files"].append(original_path.name)

        region_path = target_dir / "01_projector_region.png"
        _save_rgb_image(region_path, _draw_projector_region(proj.width, proj.height, crop_rect))
        target_report["saved_files"].append(region_path.name)

        prepared = prepare_target_image_for_compensation(
            target_image,
            target_image_space,
            pixel_map_path,
            proj.width,
            proj.height,
            camera_width,
            camera_height,
            warp_method,
        )
        prepared_path = target_dir / "02_prepared_for_compensation.png"
        _save_rgb_image(prepared_path, prepared)
        target_report["saved_files"].append(prepared_path.name)

        if target_image_space == "projector":
            projector_canvas = _build_projector_canvas(
                target_image,
                proj.width,
                proj.height,
            )
            canvas_path = target_dir / "03_projector_canvas_source.png"
            _save_rgb_image(canvas_path, projector_canvas)
            target_report["saved_files"].append(canvas_path.name)

            projector_to_camera = invwarp_image(
                target_image,
                pixel_map_path,
                proj.width,
                proj.height,
                camera_width,
                camera_height,
                warp_method=warp_method,
            )
            projector_to_camera_path = target_dir / "04_projector_to_camera_preview.png"
            _save_rgb_image(projector_to_camera_path, projector_to_camera)
            target_report["saved_files"].append(projector_to_camera_path.name)

            roundtrip_projector = warp_image(
                projector_to_camera,
                pixel_map_path,
                proj.width,
                proj.height,
                target_image.shape[1],
                target_image.shape[0],
                warp_method=warp_method,
            )
            roundtrip_path = target_dir / "05_roundtrip_camera_to_projector.png"
            _save_rgb_image(roundtrip_path, roundtrip_projector)
            target_report["saved_files"].append(roundtrip_path.name)
        else:
            camera_to_projector = warp_image(
                target_image,
                pixel_map_path,
                proj.width,
                proj.height,
                target_image.shape[1],
                target_image.shape[0],
                warp_method=warp_method,
            )
            camera_to_projector_path = target_dir / "03_camera_to_projector_preview.png"
            _save_rgb_image(camera_to_projector_path, camera_to_projector)
            target_report["saved_files"].append(camera_to_projector_path.name)

            roundtrip_camera = invwarp_image(
                camera_to_projector,
                pixel_map_path,
                proj.width,
                proj.height,
                camera_width,
                camera_height,
                warp_method=warp_method,
            )
            roundtrip_path = target_dir / "04_roundtrip_projector_to_camera.png"
            _save_rgb_image(roundtrip_path, roundtrip_camera)
            target_report["saved_files"].append(roundtrip_path.name)

        all_warnings.extend(target_report["warnings"])
        report["targets"].append(target_report)

    report_path = debug_dir / "report.json"
    report_path.write_text(
        json.dumps(report, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print(f"Saved warp debug outputs to: {debug_dir}")
    print(f"Report written to: {report_path}")
    if all_warnings:
        print("Warnings:")
        for warning in all_warnings:
            print(f"- {warning}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
